# Generated by Django 2.2.5 on 2019-10-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_conatct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
